version: '3.7'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server-app:
    volumes:
      - ./:/opt/inquiry-yoga
    ports:
      - 3000:3000
    entrypoint: bash
    command: -c 'cd keystone && yarn dev'
